[package]
name = "xdg-user-dirs"
version = "0.0.1"
description = "A library that looks up the current path for one of the XDG user directories."
keywords = ["linux", "xdg", "path"]
categories = ["filesystem"]
homepage = "https://github.com/souk4711/xdg-user-dirs"
repository = "https://github.com/souk4711/xdg-user-dirs"
include = ["src/**/*", "LICENSE-APACHE", "LICENSE-MIT", "README.md"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
edition = "2024"
